
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: monthly_expense_tracker
      MYSQL_ROOT_PASSWORD: Rrka@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    image: springboot-app
    build: .
    container_name: springboot-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/monthly_expense_tracker?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rrka@123

volumes:
  mysql_data:
